package com.bgylde.ticket.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bgylde.ticket.database.CookieModel;
import com.bgylde.ticket.database.OrderModel;
import com.bgylde.ticket.database.StationInfoModel;

import com.bgylde.ticket.database.dao.CookieModelDao;
import com.bgylde.ticket.database.dao.OrderModelDao;
import com.bgylde.ticket.database.dao.StationInfoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookieModelDaoConfig;
    private final DaoConfig orderModelDaoConfig;
    private final DaoConfig stationInfoModelDaoConfig;

    private final CookieModelDao cookieModelDao;
    private final OrderModelDao orderModelDao;
    private final StationInfoModelDao stationInfoModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookieModelDaoConfig = daoConfigMap.get(CookieModelDao.class).clone();
        cookieModelDaoConfig.initIdentityScope(type);

        orderModelDaoConfig = daoConfigMap.get(OrderModelDao.class).clone();
        orderModelDaoConfig.initIdentityScope(type);

        stationInfoModelDaoConfig = daoConfigMap.get(StationInfoModelDao.class).clone();
        stationInfoModelDaoConfig.initIdentityScope(type);

        cookieModelDao = new CookieModelDao(cookieModelDaoConfig, this);
        orderModelDao = new OrderModelDao(orderModelDaoConfig, this);
        stationInfoModelDao = new StationInfoModelDao(stationInfoModelDaoConfig, this);

        registerDao(CookieModel.class, cookieModelDao);
        registerDao(OrderModel.class, orderModelDao);
        registerDao(StationInfoModel.class, stationInfoModelDao);
    }
    
    public void clear() {
        cookieModelDaoConfig.clearIdentityScope();
        orderModelDaoConfig.clearIdentityScope();
        stationInfoModelDaoConfig.clearIdentityScope();
    }

    public CookieModelDao getCookieModelDao() {
        return cookieModelDao;
    }

    public OrderModelDao getOrderModelDao() {
        return orderModelDao;
    }

    public StationInfoModelDao getStationInfoModelDao() {
        return stationInfoModelDao;
    }

}
