package com.bgylde.ticket.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bgylde.ticket.database.CookieModel;
import com.bgylde.ticket.database.UserConfigModel;

import com.bgylde.ticket.database.dao.CookieModelDao;
import com.bgylde.ticket.database.dao.UserConfigModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cookieModelDaoConfig;
    private final DaoConfig userConfigModelDaoConfig;

    private final CookieModelDao cookieModelDao;
    private final UserConfigModelDao userConfigModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cookieModelDaoConfig = daoConfigMap.get(CookieModelDao.class).clone();
        cookieModelDaoConfig.initIdentityScope(type);

        userConfigModelDaoConfig = daoConfigMap.get(UserConfigModelDao.class).clone();
        userConfigModelDaoConfig.initIdentityScope(type);

        cookieModelDao = new CookieModelDao(cookieModelDaoConfig, this);
        userConfigModelDao = new UserConfigModelDao(userConfigModelDaoConfig, this);

        registerDao(CookieModel.class, cookieModelDao);
        registerDao(UserConfigModel.class, userConfigModelDao);
    }
    
    public void clear() {
        cookieModelDaoConfig.clearIdentityScope();
        userConfigModelDaoConfig.clearIdentityScope();
    }

    public CookieModelDao getCookieModelDao() {
        return cookieModelDao;
    }

    public UserConfigModelDao getUserConfigModelDao() {
        return userConfigModelDao;
    }

}
