package com.bgylde.ticket.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bgylde.ticket.database.StringConverter;
import java.util.List;

import com.bgylde.ticket.database.UserConfigModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "UserConfigTable".
*/
public class UserConfigModelDao extends AbstractDao<UserConfigModel, Long> {

    public static final String TABLENAME = "UserConfigTable";

    /**
     * Properties of entity UserConfigModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ConfigId = new Property(0, long.class, "configId", true, "_id");
        public final static Property FromStation = new Property(1, String.class, "fromStation", false, "FROM_STATION");
        public final static Property ToStation = new Property(2, String.class, "toStation", false, "TO_STATION");
        public final static Property StationDate = new Property(3, String.class, "stationDate", false, "STATION_DATE");
        public final static Property TrainCodeList = new Property(4, String.class, "trainCodeList", false, "TRAIN_CODE_LIST");
    }

    private DaoSession daoSession;

    private final StringConverter stationDateConverter = new StringConverter();
    private final StringConverter trainCodeListConverter = new StringConverter();

    public UserConfigModelDao(DaoConfig config) {
        super(config);
    }
    
    public UserConfigModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"UserConfigTable\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE ," + // 0: configId
                "\"FROM_STATION\" TEXT NOT NULL ," + // 1: fromStation
                "\"TO_STATION\" TEXT NOT NULL ," + // 2: toStation
                "\"STATION_DATE\" TEXT," + // 3: stationDate
                "\"TRAIN_CODE_LIST\" TEXT);"); // 4: trainCodeList
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"UserConfigTable\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserConfigModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getConfigId());
        stmt.bindString(2, entity.getFromStation());
        stmt.bindString(3, entity.getToStation());
 
        List stationDate = entity.getStationDate();
        if (stationDate != null) {
            stmt.bindString(4, stationDateConverter.convertToDatabaseValue(stationDate));
        }
 
        List trainCodeList = entity.getTrainCodeList();
        if (trainCodeList != null) {
            stmt.bindString(5, trainCodeListConverter.convertToDatabaseValue(trainCodeList));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserConfigModel entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getConfigId());
        stmt.bindString(2, entity.getFromStation());
        stmt.bindString(3, entity.getToStation());
 
        List stationDate = entity.getStationDate();
        if (stationDate != null) {
            stmt.bindString(4, stationDateConverter.convertToDatabaseValue(stationDate));
        }
 
        List trainCodeList = entity.getTrainCodeList();
        if (trainCodeList != null) {
            stmt.bindString(5, trainCodeListConverter.convertToDatabaseValue(trainCodeList));
        }
    }

    @Override
    protected final void attachEntity(UserConfigModel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public UserConfigModel readEntity(Cursor cursor, int offset) {
        UserConfigModel entity = new UserConfigModel( //
            cursor.getLong(offset + 0), // configId
            cursor.getString(offset + 1), // fromStation
            cursor.getString(offset + 2), // toStation
            cursor.isNull(offset + 3) ? null : stationDateConverter.convertToEntityProperty(cursor.getString(offset + 3)), // stationDate
            cursor.isNull(offset + 4) ? null : trainCodeListConverter.convertToEntityProperty(cursor.getString(offset + 4)) // trainCodeList
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserConfigModel entity, int offset) {
        entity.setConfigId(cursor.getLong(offset + 0));
        entity.setFromStation(cursor.getString(offset + 1));
        entity.setToStation(cursor.getString(offset + 2));
        entity.setStationDate(cursor.isNull(offset + 3) ? null : stationDateConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setTrainCodeList(cursor.isNull(offset + 4) ? null : trainCodeListConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserConfigModel entity, long rowId) {
        entity.setConfigId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserConfigModel entity) {
        if(entity != null) {
            return entity.getConfigId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserConfigModel entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
